### ISSUE TITLE
Move menu from top to status bar.

### ISSUE THREAD

**Issue by RB-Lab** [p4bl1t0/brackets-languageswitcher#1]
It would be better to move language menu from top menu panel to status bar and make it as drop-down list as it made, for example, in gedit (or in [this extension](https://github.com/asotog/codehighlighter-switcher-bracketsio)). Or at least to move it as submenu of "view" menu. Since there is not so much room in top menu bar.

**Comment by p4bl1t0** [comment]
The extesion development is now stopped. 

Waiting untill [this pull request](https://github.com/adobe/brackets/pull/6409) meet a realese version or not.
