### ISSUE TITLE
Remove from extension registry?

### ISSUE THREAD

**Issue by peterflynn** [p4bl1t0/brackets-languageswitcher#3]
Since there's a built-in Brackets feature to do this now -- integrated with Brackets preferences, too -- I wonder if this extension should be removed from the registry to avoid confusion?

**Comment by p4bl1t0** [comment]
Yes, sure! I am agree.

2015-01-08 20:59 GMT-03:00 Peter Flynn notifications@github.com:

**Comment by peterflynn** [comment]
@p4bl1t0 It is still listed though :-)  To remove the extension, [sign into the Extension Registry](https://brackets-registry.aboutweb.com/), search for your extension in the list, and then click the Delete button.

**Comment by p4bl1t0** [comment]
Sorry, I miss understand you. I think you were asking me to deleted yourself. Now it is already done.

Thank you.
